# Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. By starting with 1 and 2, the first 10 terms 
# will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do 
# not exceed four million, find the sum of the even-valued terms.

require './lib/problem-0002'

describe 'solution' do

  it 'sums the first two terms to generate the third term' do
    expect(Problem2.fib(13)).to eq 10
  end

  it 'sums the even-valued terms up to the limit' do
    expect(Problem2.fib(4000000)).to eq 4613732
  end

end